In [ ]:
# Import python Libirary
import numpy as np

In [ ]:
# 1.Creating Array
arr = np.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [ ]:
# 2.Access Array Elements
arr = np.array([1,2,3,4,5])
print(arr[1])
print(arr[1]+arr[2])

2
5


In [ ]:
#2.1 Access 2-D Arrays
arry = np.array([[1,2,3,4], [5,6,7,8]])
print(arry)
print("Scond Row First Element:",arry[1,0])
print("Fourth Elemnt of Scond Row:",arry[1,3])

[[1 2 3 4]
 [5 6 7 8]]
Scond Row First Element: 5
Fourth Elemnt of Scond Row: 8


In [ ]:
# 2.2Access 3-D Arrays

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr)
print(arr[0, 1, 2])

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
6


In [ ]:
# 3.Array Operation
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

print(arr.ndim)   # dimensions
print(arr.shape)  # rows, columns
print(arr.size)   # total elements
print(arr.dtype)  # data type

2
(2, 3)
6
int64


In [ ]:
# 4.Range Function Use
arry = np.arange(10)
print(arry)
arr1 = np.arange(1,10,2)
print(arr1)

[0 1 2 3 4 5 6 7 8 9]
[1 3 5 7 9]


In [ ]:
# 5. Crating Matrix
a = np.zeros((3,3))
print(a)
b = np.ones((3,4))
print(b)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
#  6.Indexing and Slicing
array = np.array([9,8,7,65,4,3,2,1])
print(arry[0])
print(arry[-1])
print(arry[1:4])
print(arry[:3])
print(arry[::-1])

0
9
[1 2 3]
[0 1 2]
[9 8 7 6 5 4 3 2 1 0]


In [ ]:
# 7.Arithmetic Operations
array1 = np.array([1,2,3,4])

print(array1 + 10)
print(array1 - 10)
print(array1 * 10)
print(array1 / 2)
print(array1 ** 2)

[11 12 13 14]
[-9 -8 -7 -6]
[10 20 30 40]
[0.5 1.  1.5 2. ]
[ 1  4  9 16]


In [ ]:
# 8.. Array vs Array Operations
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(a + b)
print(a * b)

[5 7 9]
[ 4 10 18]


In [ ]:
# 9. Boolean Indexing / Filtering
arr = np.array([10, 20, 30, 40, 50])

print(arr[arr > 25])
print(arr[(arr >= 20) & (arr <= 40)])

[30 40 50]
[20 30 40]


In [ ]:
# 10.Statistical Functions
array = np.array([10,20,30,40,50])
print("Mean:",np.mean(array))
print("Median:",np.median(array))
print("Sum:",np.sum(array))
print("Minimum:",np.min(array))
print("Maximum:",np.max(array))
print("Standered Deivation:",np.std(array))

Mean: 30.0
Median: 30.0
Sum: 150
Minimum: 10
Maximum: 50
Standered Deivation: 14.142135623730951


In [ ]:
# 11.Reshape Array
array = np.arange(12)
print(array)
new_array = array.reshape(3,4)
print(new_array)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [ ]:
# 12.Convert 2D array into 1D
arr = np.array([[1,2,3,4],[5,6,7,8]])
print(arr)
print(arr.flatten())

[[1 2 3 4]
 [5 6 7 8]]
[1 2 3 4 5 6 7 8]


In [ ]:
# 13. Axis Calculaton
arr = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
print(np.sum(arr, axis=1))
print(np.sum(arr,axis=0))

[ 6 15]
[5 7 9]


In [ ]:
# 14.Sorting and Unique Values
arr = np.array([5, 2, 8, 2, 1])

print(np.sort(arr))
print(np.unique(arr))

[1 2 2 5 8]
[1 2 5 8]


In [ ]:
# 15. Random Number
np.random.rand(3, 3)
np.random.randint(1, 100, 10)

array([62, 23, 47, 89, 43, 65, 61, 66,  5, 23])

In [ ]:
# Practise Question 1
#An online store recorded the number of products sold each day:

#sales = np.array([120, 150, 98, 200, 175, 90, 220])
#Task:
#1.Find total products sold.
#2.Find average daily sales.
#3.Find the highest and lowest sales.
#4.Find all days where sales were greater than 150.
#5.Find the day number with the highest sales.

sales = np.array([120, 150, 98, 200, 175, 90, 220])
#1.Find total products sold
print("Total Product Sold:",np.sum(sales))

#2.Find average daily sales
print("Average Daily Sales is:",np.mean(sales))

#3.Find the highest and lowest sales.
print("Highest Sales is:",np.max(sales))
print("Lowest Sales is:",np.min(sales))

#4.Find all days where sales were greater than 150
print("Days where sales  is greayher than 150:",sales[sales > 150])

#5.Find the day number with the highest sales.
print("Highest Sales Day is :",np.argmax(sales))

Total Product Sold: 1053
Average Daily Sales is: 150.42857142857142
Highest Sales is: 220
Lowest Sales is: 90
Days where sales  is greayher than 150: [200 175 220]
Highest Sales Day is : 6


In [ ]:
from ast import Num
"""
2. Student Performance Analysis 🎓

A teacher has marks of 5 students in 3 subjects:

marks = np.array([
    [85, 90, 78],
    [65, 70, 60],
    [95, 88, 92],
    [40, 55, 48],
    [75, 80, 85]
])
Task:
Find the average marks of each student.
Find the average marks for each subject.
Find the highest mark in the entire class.
Find students whose average is greater than 80.
Find the total marks of each student
"""

# Question 2


marks = np.array([
    [85, 90, 78],
    [65, 70, 60],
    [95, 88, 92],
    [40, 55, 48],
    [75, 80, 85]
])

#1.Find the average marks of each student.
print("Average Marks of Each Student:",np.mean(marks,axis=1))

#2.Find the average marks for each subject
print("Average Marks Of Each Subject is:",np.mean(marks,axis=0))

#3.Find the highest mark in the entire class
print("Highest Mark is :",np.max(marks))

#4.Find students whose average is greater than 80

print("Student whose average graeter than 80:",np.mean(marks,axis=1)>80)

#5.Find the total marks of each student
print("Total Marks of Each Student is:",np.sum(marks,axis=1))


Average Marks of Each Student: [84.33333333 65.         91.66666667 47.66666667 80.        ]
Average Marks Of Each Subject is: [72.  76.6 72.6]
Highest Mark is : 95
Student whose average graeter than 80: [ True False  True False False]
Total Marks of Each Student is: [253 195 275 143 240]


In [ ]:
"""
3. Company Employee Salary 💼

A company stores monthly salaries:

salary = np.array([25000, 32000, 45000, 28000, 55000, 38000])
Task:
Find the average salary.
Find employees earning more than ₹35,000.
Give every employee a 10% salary increase.
Find the highest salary after the increase.
Sort salaries from lowest to highest.
"""
# Question 3

salary = np.array([25000, 32000, 45000, 28000, 55000, 38000])

#1.Find the average salary.
print("Average Salary is(Rs):",np.mean(salary))

#2.Find employees earning more than ₹35,000.
print("Employees earning more than ₹35000:",salary[salary>35000])

#3.Give every employee a 10% salary increase
hike = salary * 0.1
new_salary = salary + hike
print("10% Hike After Employee Salary:",new_salary)

#4.Find the highest salary after the increase.
high_salary = np.max(new_salary)
print("Highest Salary after Giving 10% hike:",high_salary)

#5.Sort salaries from lowest to highest.
print("Sort Salaries is :",np.sort(salary))

Average Salary is(Rs): 37166.666666666664
Employees earning more than ₹35000: [45000 55000 38000]
10% Hike After Employee Salary: [27500. 35200. 49500. 30800. 60500. 41800.]
Highest Salary after Giving 10% hike: 60500.0
Sort Salaries is : [25000 28000 32000 38000 45000 55000]
